### ISSUE TITLE
Use Different Rickroll link.

### ISSUE THREAD

**Issue by bc-185** [jere-mie/routing-prank#2]
I found a flaw in the redirect. The flaw is that it uses the official music video, which contains ads. These ADs can allow the person realize that they are about to be rickrolled and close the video. I found this HD rickroll with no ads that you should use instead.
https://www.youtube.com/watch?v=xMHJGd3wwZk

**Comment by jere-mie** [comment]
This is no longer an issue as the new website no longer uses a YouTube video to Rick Roll people. Instead, a gif is used on a webpage.
I'm happy to see people are interested in the project though :)
